config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  resources :unicorns do 
  	resources(:reviews, { only: [:new, :create] })
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :unicorn
end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
	has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  	@unicorn = Unicorn.find(params[:unicorn_id])
  	@review = Review.new
  end

  def create
  	@unicorn = Unicorn.find(params[:unicorn_id])

  	@review = Review.new(review_params)
  	@review.unicorn = @unicorn
  	# @review.unicorn_id = params[:unicorn_id]
  	# @review.unicorn_id = @unicorn.id

  	@review.save

  	redirect_to unicorns_path
  end

  def review_params
  	params.require(:review).permit(:author, :content, :rating)
  end
end

app/controllers/unicorns_controller.rb
class UnicornsController < ApplicationController
  before_action :set_unicorn, only: [:show, :edit, :update, :destroy]

  # GET /unicorns
  # GET /unicorns.json
  def index
    @unicorns = Unicorn.all
  end

  # GET /unicorns/1
  # GET /unicorns/1.json
  def show
  end

  # GET /unicorns/new
  def new
    @unicorn = Unicorn.new
  end

  # GET /unicorns/1/edit
  def edit
  end

  # POST /unicorns
  # POST /unicorns.json
  def create
    @unicorn = Unicorn.new(unicorn_params)

    respond_to do |format|
      if @unicorn.save
        format.html { redirect_to @unicorn, notice: 'Unicorn was successfully created.' }
        format.json { render :show, status: :created, location: @unicorn }
      else
        format.html { render :new }
        format.json { render json: @unicorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unicorns/1
  # PATCH/PUT /unicorns/1.json
  def update
    respond_to do |format|
      if @unicorn.update(unicorn_params)
        format.html { redirect_to @unicorn, notice: 'Unicorn was successfully updated.' }
        format.json { render :show, status: :ok, location: @unicorn }
      else
        format.html { render :edit }
        format.json { render json: @unicorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unicorns/1
  # DELETE /unicorns/1.json
  def destroy
    @unicorn.destroy
    respond_to do |format|
      format.html { redirect_to unicorns_url, notice: 'Unicorn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unicorn
      @unicorn = Unicorn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unicorn_params
      params.require(:unicorn).permit(:name, :color, :horn_type, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/unicorns_helper.rb
module UnicornsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnicornMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@unicorn, @review] do |f| %>
	<%= f.input :author %>
	<%= f.input :content %>
	<%= f.input :rating, collection: (0..5) %>
	<%= f.submit %> 
<% end %>

app/views/unicorns/_form.html.erb
<%= form_with(model: unicorn, local: true) do |form| %>
  <% if unicorn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unicorn.errors.count, "error") %> prohibited this unicorn from being saved:</h2>

      <ul>
      <% unicorn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :unicorn_name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :unicorn_color %>
  </div>

  <div class="field">
    <%= form.label :horn_type %>
    <%= form.text_field :horn_type, id: :unicorn_horn_type %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :unicorn_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unicorns/edit.html.erb
<h1>Editing Unicorn</h1>

<%= render 'form', unicorn: @unicorn %>

<%= link_to 'Show', @unicorn %> |
<%= link_to 'Back', unicorns_path %>

app/views/unicorns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unicorns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Horn type</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unicorns.each do |unicorn| %>
      <tr>
        <td><%= unicorn.name %></td>
        <td><%= unicorn.color %></td>
        <td><%= unicorn.horn_type %></td>
        <td><%= unicorn.age %></td>
        <td><%= link_to 'Show', unicorn %></td>
        <td><%= link_to 'Edit', edit_unicorn_path(unicorn) %></td>
        <td><%= link_to 'Destroy', unicorn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unicorn', new_unicorn_path %>

app/views/unicorns/new.html.erb
<h1>New Unicorn</h1>

<%= render 'form', unicorn: @unicorn %>

<%= link_to 'Back', unicorns_path %>

app/views/unicorns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unicorn.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @unicorn.color %>
</p>

<p>
  <strong>Horn type:</strong>
  <%= @unicorn.horn_type %>
</p>

<p>
  <strong>Age:</strong>
  <%= @unicorn.age %>
</p>

<%= link_to 'Edit', edit_unicorn_path(@unicorn) %> |
<%= link_to 'Back', unicorns_path %>

<h1>Reviews</h1>
<ul>
<% @unicorn.reviews.each do |review| %>
	<li>
		<%= review.content %>
		<%= "★" * review.rating %>
	</li>

<% end %>
</ul>